name: CI - Integração Contínua

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.407
        
    - name: Restore dependencies
      run: dotnet restore ./src
      
    - name: Build
      run: dotnet build --no-restore  ./src
    
    - name: Testes Automatizados      
      run: dotnet test ./src/Api.Data.Test/Api.Data.Test.csproj --verbosity minimal
